version: v0.2.0
input:
  root: RootObject
  objects:
    RootObject:
      id: RootObject
      properties:
        coremark_pro_params:
          type:
            type_id: ref
            id: TuneIterationsInput
            namespace: $.steps.tune_iterations.starting.inputs.input

steps:
  metadata:
    plugin:
      deployment_type: image
      src: quay.io/arcalot/arcaflow-plugin-metadata:0.4.0
    input: {}
  # Tune the iterations to the target time
  tune_iterations:
    plugin:
      deployment_type: image
      src: quay.io/arcalot/arcaflow-plugin-coremark-pro:fix-multithread_13d353f
    step: tune-iterations
    input: !expr $.input.coremark_pro_params

  foreach_loop:
    kind: foreach
    items:
      - coremark_pro_params: !expr $.steps.tune_iterations.outputs.success
      - coremark_pro_params: !expr $.steps.tune_iterations.outputs.success
      - coremark_pro_params: !expr $.steps.tune_iterations.outputs.success
      - coremark_pro_params: !expr $.steps.tune_iterations.outputs.success
      - coremark_pro_params: !expr $.steps.tune_iterations.outputs.success
    workflow: sub-workflow.yaml
    parallelism: 1

outputs:
  success:
    metadata: !expr $.steps.metadata.outputs.success
    coremark_pro_results: !expr $.steps.foreach_loop.outputs.success.data
